[supervisord]
nodaemon=true

[program:dbus]
command=/usr/bin/dbus-daemon --system --nofork

[program:xrdp-sesman]
command=/usr/sbin/xrdp-sesman --nodaemon

[program:xrdp]
command=/usr/sbin/xrdp --nodaemon

[program:vnc]
command=/usr/bin/tigervncserver -xstartup /usr/bin/startx -localhost no -PasswordFile /home/developer/.vnc/passwd -desktop lxde :1
user=developer

[program:app]
command=python3 -m gunicorn --worker-class eventlet -w 1 -b 0.0.0.0:8080 web.app:app
directory=/app
user=developer
